object DependencyVersion {
    const val DAGGER="2.36"
    const val COREKTX="1.5.0"
    const val APPCOMPACT="1.3.0"

    const val CONSTRAINT="2.0.4"
    const val SUPPORTLEGACY="1.0.0"
    const val CARDVIEW="1.0.0"
    const val RECYCLERVIEW="1.2.0"
    const val MATERIALDESING="1.4.0-beta01"
    const val SHIMMER="0.5.0"
    const val FRAGMENT_KTX = "1.3.4"
    const val DATABINDING = "3.1.4"
    const val KARUMI="6.2.1"
    const val PRETTYTIME="4.0.4.Final"
    const val LIVEDATA="2.4.0-alpha01"
    const val COROUTINESANDROID="1.3.9"
    const val LIFECYCLEKTX="2.4.0-alpha01"
    const val LIFECYCLEEXTENSION="1.5.0"
    const val DATASTORE="1.0.0-beta01"
    const val GLIDE="4.11.0"
    const val GLIDECOMPILER="4.9.0"
    const val GLIDETRANSFORMATION="4.3.0"
    const val NAVIGATION="2.3.5"
    const val ROOM="2.3.0"
    const val HUAWEI="1.4.1.300"
    const val FIRESTORE="23.0.0"
    const val FIREBASEREALTIME="20.0.0"
    const val FIREBASESTORAGE="20.0.0"
    const val CAMERAX="1.1.0-alpha04"
    const val CAMERAXVIEW="1.0.0-alpha24"
    const val RETROFIT="2.7.2"
    const val CONVERTER="2.9.0"
    const val LOGGING = "4.9.0"
    const val GROUPIE="2.8.1"
    const val GPUIMAGE="2.1.0"
    const val MAPSUTIL="2.2.0"
    const val KLAXON="5.0.1"
    const val CIRCLEIMAGE="3.1.0"
    const val SWIPEDECORATOR="1.2.3"
    const val RXANDROID="2.1.1"
    const val RXJAVA="2.2.10"
    const val LOTTIE="3.7.0"

    const val COIL = "1.2.2"

    // Tests
    const val COROUTINESTEST = "1.5.0"
    const val TEST = "1.3.0"
    const val EXT = "1.1.2"
    // Truth Assertion
    const val truthVersion = "1.0.1"
    const val ARCH_CORE = "2.1.0"
    // Junit5
    const val junit5Version = "5.4.0"
    const val ROBOELECTRIC = "4.4"
    const val MOCKK = "1.10.2"
}